spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3310/meeting?createDatabaseIfNotExist=true
    username: meeting
    password: meeting
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: meeting-service

server:
  port: 8093
  error:
    include-binding-errors: always
    include-message: always

eureka:
  client:
    service-url: http://localhost:8761/eureka




