
version: '3.8'

services:
  userdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./userdb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user

  scheduledb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./scheduledb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: schedule
      MYSQL_USER: schedule
      MYSQL_PASSWORD: schedule
      MYSQL_ROOT_PASSWORD: schedule

  meetupdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3310:3306
    volumes:
      - ./meetupdb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting
      MYSQL_USER: meeting
      MYSQL_PASSWORD: meeting
      MYSQL_ROOT_PASSWORD: meeting

  managementdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3310:3306
    volumes:
      - ./managementdb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: management
      MYSQL_PASSWORD: management
      MYSQL_ROOT_PASSWORD: management

  chatdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3311:3306
    volumes:
      - ./chatdb-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
      MYSQL_ROOT_PASSWORD: chat

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080