
version: '3.8'

services:
  userdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root

  scheduledb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: schedule
      MYSQL_USER: schedule
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root

  meetupdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meetup
      MYSQL_USER: meetup
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root

  managementdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3310:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: management
      MYSQL_USER: management
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root

  chatdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - "3311:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: chat
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080