
version: '3.8'

services:
  userdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  scheduledb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root

  meetupdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3309:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  managementdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3310:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  chatdb:
    image: mysql:latest
    platform: linux/amd64
    restart: always
    ports:
      - 3311:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  adminer:
    image: adminer
    platform: linux/amd64
    restart: always
    ports:
      - 18080:8080