
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/user?createDatabaseIfNotExist=true
    username: user
    password: user
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: USER-SERVICE

server:
  port: 8094
  error:
    include-binding-errors: always
    include-message: always


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/








logging:
  level:
    root: INFO