spring:
  application:
    name: schedule-service
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3308/schedule?createDatabaseIfNotExist=true
    username: schedule
    password: schedule
    driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8096
  error:
    include-message: always

