spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3310/management?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

  application:
    name: COMMUNITY-SERVICE

server:
  port: 8095
  error:
    include-binding-errors: always
    include-message: always

eureka:
  client:
    service-url: http://localhost:8761/eureka




