spring:
  application:
    name: chat-service
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3311/chat?createDatabaseIfNotExist=true
    username: chat
    password: chat
    driverClassName: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



server:
  port: 8091
  error:
    include-message: always

